CREATE DATABASE IF NOT EXISTS absensi_sman5 CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci; USE absensi_sman5;
CREATE TABLE admin(id INT AUTO_INCREMENT PRIMARY KEY,username VARCHAR(50) UNIQUE NOT NULL,password_hash VARCHAR(255) NOT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE kelas(id INT AUTO_INCREMENT PRIMARY KEY,nama VARCHAR(50) NOT NULL UNIQUE);
CREATE TABLE siswa(id INT AUTO_INCREMENT PRIMARY KEY,nisn VARCHAR(30) UNIQUE NOT NULL,nama VARCHAR(150) NOT NULL,kelas_id INT NOT NULL,jenis_kelamin ENUM('L','P') DEFAULT 'L',descriptor_json LONGTEXT NULL,aktif TINYINT(1) DEFAULT 1,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(kelas_id) REFERENCES kelas(id));
CREATE TABLE absensi(id BIGINT AUTO_INCREMENT PRIMARY KEY,siswa_id INT NOT NULL,tanggal DATE NOT NULL,jam TIME NOT NULL,status ENUM('Hadir','Sakit','Izin','Alpa') NOT NULL DEFAULT 'Hadir',metode VARCHAR(30) DEFAULT 'Wajah',created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,UNIQUE KEY satu_hari(siswa_id,tanggal),FOREIGN KEY(siswa_id) REFERENCES siswa(id));
INSERT INTO kelas(nama) VALUES ('X'),('XI'),('XII') ON DUPLICATE KEY UPDATE nama=VALUES(nama);
