const API=window.APP_CONFIG.API_BASE_URL;const video=document.getElementById('video'),overlay=document.getElementById('overlay'),statusEl=document.getElementById('status');let stream=null,scanning=false,students=[];
const api=async(path,opt={})=>{const r=await fetch(API+'/'+path,{headers:{'Content-Type':'application/json',...(opt.headers||{})},...opt});if(!r.ok)throw new Error(await r.text());return r.json()};
async function load(){try{const d=await api('attendance.php?action=today');render(d.rows||[]);document.getElementById('hadir').textContent=d.counts?.hadir||0;document.getElementById('sakit').textContent=d.counts?.sakit||0;document.getElementById('izin').textContent=d.counts?.izin||0;document.getElementById('alpa').textContent=d.counts?.alpa||0}catch(e){statusEl.textContent='Backend belum terhubung. Isi API_BASE_URL terlebih dahulu.'}}
function render(rows){document.getElementById('recentBody').innerHTML=rows.slice(0,15).map(x=>`<tr><td>${esc(x.nama)}</td><td>${esc(x.kelas)}</td><td>${esc(x.jam)}</td><td>${esc(x.status)}</td></tr>`).join('')}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
async function start(){try{statusEl.textContent='Memuat model wajah...';await Promise.all(['tiny_face_detector','face_landmark_68','face_recognition'].map(x=>faceapi.nets[x].loadFromUri('https://justadudewhohacks.github.io/face-api.js/models')));students=await api('students.php?action=descriptors');stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user',width:{ideal:640},height:{ideal:480}},audio:false});video.srcObject=stream;await video.play();overlay.width=video.videoWidth;overlay.height=video.videoHeight;scanning=true;statusEl.textContent='Kamera aktif — hadapkan wajah';scan()}catch(e){statusEl.textContent='Gagal memulai kamera/model: '+e.message}}
async function scan(){if(!scanning)return;const opts=new faceapi.TinyFaceDetectorOptions({inputSize:320,scoreThreshold:.5});const results=await faceapi.detectAllFaces(video,opts).withFaceLandmarks().withFaceDescriptors();const ctx=overlay.getContext('2d');ctx.clearRect(0,0,overlay.width,overlay.height);if(results.length){const best=results[0];const match=findMatch(best.descriptor);if(match){statusEl.textContent=`Wajah dikenali: ${match.nama} (${match.kelas})`;try{await api('attendance.php',{method:'POST',body:JSON.stringify({siswa_id:match.id,status:'Hadir'})});await load();}catch(e){statusEl.textContent=e.message}await new Promise(r=>setTimeout(r,1800));statusEl.textContent='Kamera aktif — hadapkan wajah berikutnya'}}requestAnimationFrame(scan)}
function findMatch(desc){let best=null,dist=.5;for(const s of students){if(!s.descriptor)continue;const d=faceapi.euclideanDistance(desc,new Float32Array(s.descriptor));if(d<dist){dist=d;best=s}}return best}
document.getElementById('startBtn').onclick=start;document.getElementById('refreshBtn').onclick=load;document.getElementById('adminBtn').onclick=()=>document.getElementById('adminModal').classList.remove('hidden');document.getElementById('closeModal').onclick=()=>document.getElementById('adminModal').classList.add('hidden');document.getElementById('loginBtn').onclick=async()=>{try{const d=await api('auth.php',{method:'POST',body:JSON.stringify({username:username.value,password:password.value})});localStorage.token=d.token;location.href='admin.html'}catch(e){document.getElementById('loginMsg').textContent='Login gagal'}};load();
